import type { Exam } from './types';

export const exams: Exam[] = [
  {
    id: 'EXM001',
    patientName: 'João da Silva',
    patientId: '123.456.789-01',
    patientDob: '1985-05-15',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    destination: 'Laboratório Central',
    result: 'https://example.com/results/joaosilva.pdf',
    observations: 'Paciente em jejum de 8 horas.',
    receivedDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    withdrawnBy: 'Ana Costa',
  },
  {
    id: 'EXM002',
    patientName: 'Maria Oliveira',
    patientId: '987.654.321-02',
    patientDob: '1992-08-22',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    destination: 'São João',
    observations: 'Uso de contraste.',
  },
  {
    id: 'EXM003',
    patientName: 'Alice Johnson',
    patientId: '456.789.123-03',
    patientDob: '1978-11-30',
    collectionDate: new Date().toISOString(),
    destination: 'Laboratório Central',
  },
  {
    id: 'EXM004',
    patientName: 'Robert Brown',
    patientId: '321.654.987-04',
    patientDob: '2001-02-10',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    destination: 'Clínica Parceira',
    result: 'https://example.com/results/robertbrown.pdf',
    receivedDate: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    withdrawnBy: 'Carlos Pereira',
  },
  {
    id: 'EXM005',
    patientName: 'Emily Davis',
    patientId: '654.123.789-05',
    patientDob: '1995-07-19',
    collectionDate: new Date().toISOString(),
    destination: 'São João',
  },
  {
    id: 'EXM006',
    patientName: 'Michael Wilson',
    patientId: '789.123.456-06',
    patientDob: '1988-09-05',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    destination: 'Centro de Pesquisa',
    observations: 'Amostra enviada para análise patológica.',
  },
  {
    id: 'EXM007',
    patientName: 'Sarah Miller',
    patientId: '147.258.369-07',
    patientDob: '1999-12-12',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    destination: 'Laboratório Central',
    result: 'https://example.com/results/sarahmiller.pdf',
    receivedDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    withdrawnBy: 'Mariana Lima',
  },
  {
    id: 'EXM008',
    patientName: 'David Martinez',
    patientId: '258.369.147-08',
    patientDob: '1982-04-25',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    destination: 'Clínica Parceira',
  },
  {
    id: 'EXM009',
    patientName: 'Laura Garcia',
    patientId: '369.147.258-09',
    patientDob: '2005-01-08',
    collectionDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    destination: 'São João',
  },
  {
    id: 'EXM010',
    patientName: 'James Rodriguez',
    patientId: '963.852.741-10',
    patientDob: '1975-03-03',
    collectionDate: new Date().toISOString(),
    destination: 'Clínica Parceira',
  },
];


export const withdrawnByOptions = [
    { value: "Ana Costa", label: "Ana Costa" },
    { value: "Carlos Pereira", label: "Carlos Pereira" },
    { value: "Mariana Lima", label: "Mariana Lima" },
];
